DROP TABLE IF EXISTS purchase;

CREATE TABLE purchase (
  id INT PRIMARY KEY AUTO_INCREMENT,
  ITEM VARCHAR(250) NOT NULL,
  STORE VARCHAR(250) NOT NULL,
  DATE DATE NOT NULL,
  AMOUNT DECIMAL NOT NULL,
  CATEGORY VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS budget;

CREATE TABLE budget (
  id INT PRIMARY KEY AUTO_INCREMENT,
  CATEGORY VARCHAR(250) NOT NULL,
  AMOUNT DECIMAL NOT NULL
);
